Title: cli service discovery in debug mode gives traceback when not using inline snmp
Component: checks
State: open
Date: 2015-06-12 09:34:21
Targetversion: 1.2.6
Class: bug

OMD[heute]:~$ cmk --debug -vII heute
Discovering services on heute:
heute:
Running 'snmpget -v2c -c 'public' -m '' -M '' -On -OQ -Oe -Ot 127.0.0.1 .1.3.6.1.2.1.1.1.0'
SNMP answer: ==> ["Linux klappmesser 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1~bpo70+1 (2015-04-27) x86_64"]
Running 'snmpget -v2c -c 'public' -m '' -M '' -On -OQ -Oe -Ot 127.0.0.1 .1.3.6.1.2.1.1.2.0'
SNMP answer: ==> [.1.3.6.1.4.1.8072.3.2.10]
Running 'snmpget -v2c -c 'public' -m '' -M '' -On -OQ -Oe -Ot 127.0.0.1 .1.3.6.1.4.1.231.2.10.2.1.1.0'
SNMP answer: ==> [No Such Object available on this agent at this OID]
   WARNING: Exception in SNMP scan function of fsc_fans
Traceback (most recent call last):
  File "/omd/sites/heute/share/check_mk/modules/check_mk.py", line 5968, in <module>
    do_discovery(hostnames, check_types, seen_I == 1)
  File "/omd/sites/heute/share/check_mk/modules/discovery.py", line 72, in do_discovery
    do_discovery_for(hostname, check_types, only_new, use_caches, on_error)
  File "/omd/sites/heute/share/check_mk/modules/discovery.py", line 85, in do_discovery_for
    new_items = discover_services(hostname, check_types, use_caches, do_snmp_scan, on_error)
  File "/omd/sites/heute/share/check_mk/modules/discovery.py", line 304, in discover_services
    check_types = snmp_scan(hostname, ipaddress, on_error)
  File "/omd/sites/heute/share/check_mk/modules/discovery.py", line 387, in snmp_scan
    result = scan_function(oid_function)
  File "/omd/sites/heute/share/check_mk/checks/fsc_fans", line 49, in <lambda>
    oid(".1.3.6.1.4.1.231.2.10.2.1.1.0"),
  File "/omd/sites/heute/share/check_mk/modules/discovery.py", line 382, in oid_function
    value = get_single_oid(hostname, ipaddress, oid)
  File "/omd/sites/heute/share/check_mk/modules/check_mk.py", line 817, in get_single_oid
    value = snmp_get_oid(hostname, ipaddress, oid)
  File "/omd/sites/heute/share/check_mk/modules/check_mk.py", line 779, in snmp_get_oid
    if value.startswith('"') and value.endswith('"'):
AttributeError: 'NoneType' object has no attribute 'startswith'

============================================================
possible solution:

diff --git a/modules/check_mk.py b/modules/check_mk.py
index 9906bc7..6aedca7 100755
--- a/modules/check_mk.py
+++ b/modules/check_mk.py
@@ -776,7 +776,7 @@ def snmp_get_oid(hostname, ipaddress, oid):
         value = None
 
     # Strip quotes
-    if value.startswith('"') and value.endswith('"'):
+    if value and value.startswith('"') and value.endswith('"'):
         value = value[1:-1]
     return value

